[package]
name = "ray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# getrandom = {version = "0.2.8", features = ["js"]}
rayon = "1.6.1"
rand = "0.8.5"
nalgebra = "0.32.1"